version: '3.8'

x-spark-common: &spark-common
  image: bitnamilegacy/spark:3.4.1
  environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_WORKER_MEMORY=2G
    - SPARK_WORKER_CORES=2
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    - ./data:/opt/bitnami/spark/data

services:
  # ==============================
  # 1. MINIO (S3 OBJECT STORAGE)
  # ==============================
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./raw_data.csv:/raw_data.csv
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      until mc alias set myminio http://minio:9000 admin password123; do sleep 2; done;
      echo 'Creating buckets...';
      mc mb myminio/bronze --ignore-existing;
      mc mb myminio/silver --ignore-existing;
      mc mb myminio/gold --ignore-existing;
      echo 'Uploading raw data...';
      mc cp /raw_data.csv myminio/bronze/;
      echo 'MinIO Initialization complete.';
      "

  # ==============================
  # 2. APACHE SPARK (MASTER & WORKER)
  # ==============================
  spark-master:
    image: bitnamilegacy/spark:3.4.1
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data

  spark-worker:
    <<: *spark-common

  # ==============================
  # 3. POSTGRES (Metadata DB)
  # ==============================
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  # ==============================
  # 4. APACHE AIRFLOW
  # ==============================
  airflow-init:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      postgres:
        condition: service_healthy
    user: "0:0"
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "
      airflow db migrate && 
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && 
      airflow connections delete spark_default || true && 
      airflow connections add spark_default --conn-type spark --conn-host spark://spark-master --conn-port 7077
      "

  airflow-webserver:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./jobs:/opt/airflow/jobs
      - airflow_logs:/opt/airflow/logs
    command: airflow webserver

  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./jobs:/opt/airflow/jobs
      - airflow_logs:/opt/airflow/logs
    command: airflow scheduler

  # ==============================
  # 5. APACHE SUPERSET
  # ==============================
  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SUPERSET_SECRET_KEY=yoursecretkey
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
    volumes:
      - ./superset_config.py:/app/superset_config.py
    command: >
      bash -c 'pip install psycopg2-binary &&
               superset db upgrade && 
               superset fab create-admin --username admin --firstname Admin --lastname Admin --email admin@example.com --password admin && 
               superset init && 
               gunicorn -w 2 --timeout 120 -b  0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"'

volumes:
  minio_data:
  postgres_data:
  airflow_logs:
